import { artifactObjectKey, type ArtifactSubmission } from "@reliable-drive-sync/protocol/artifact";
import type { D1Database } from "./db.js";

export type ArtifactState = "dispatch_pending" | "dispatching" | "broker_queued" | "syncing" | "synced" | "needs_attention";
export type ArtifactJob = { jobId: string; artifactKey: string; candidateId: string; sessionId: string; state: ArtifactState; isNew?: boolean };
export type CandidateSummary = { candidateId: string; displayName: string | null; activeResumeArtifactKey: string | null; updatedAt: string };
export type CandidateContext = CandidateSummary & { profile: unknown; artifacts: Array<{ artifactKey: string; sessionId: string; artifactType: string; fileName: string; state: ArtifactState; createdAt: string }> };
type Statement = ReturnType<D1Database["prepare"]> & { all<T>(): Promise<{ results: T[] }> };

function map(row: Record<string, unknown>): ArtifactJob { return { jobId: String(row.job_id), artifactKey: String(row.artifact_key), candidateId: String(row.candidate_id), sessionId: String(row.session_id), state: row.state as ArtifactState }; }

/** The artifact repository is deliberately separate from event jobs: an artifact has binary R2 data and its own immutable checksum fence. */
export class D1ArtifactRepository {
  constructor(private readonly db: D1Database) {}
  async createOrGet(artifact: ArtifactSubmission): Promise<ArtifactJob | "conflict"> {
    const existing = await this.byKey(artifact.artifactKey);
    if (existing) return existing.sha256 === artifact.sha256 ? { ...map(existing), isNew: false } : "conflict";
    const now = new Date().toISOString(); const jobId = crypto.randomUUID();
    const result = await this.db.prepare(`INSERT OR IGNORE INTO artifact_jobs (job_id,artifact_key,candidate_id,session_id,artifact_type,file_name,content_type,sha256,r2_key,metadata_json,state,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?, 'dispatch_pending',?,?)`)
      .bind(jobId, artifact.artifactKey, artifact.candidateId, artifact.sessionId, artifact.artifactType, artifact.fileName, artifact.contentType, artifact.sha256, `d1://${artifactObjectKey(artifact)}`, JSON.stringify({ ...artifact, bytes: undefined }), now, now).run();
    if (result.meta?.changes === 1) await this.db.prepare(`INSERT INTO artifact_contents (artifact_key, content, byte_length, created_at) VALUES (?, ?, ?, ?)`)
      .bind(artifact.artifactKey, artifact.bytes, artifact.bytes.byteLength, now).run();
    const stored = await this.byKey(artifact.artifactKey); if (!stored) throw new Error("Artifact job was not persisted");
    if (stored.sha256 !== artifact.sha256) return "conflict";
    if (result.meta?.changes === 1) await this.upsertCandidate(artifact, now);
    return { ...map(stored), isNew: result.meta?.changes === 1 };
  }
  async listCandidates(): Promise<CandidateSummary[]> { const result = await (this.db.prepare(`SELECT candidate_id, display_name, active_resume_artifact_key, updated_at FROM interview_candidates ORDER BY updated_at DESC`) as Statement).all<Record<string, unknown>>(); return result.results.map((r) => ({ candidateId: String(r.candidate_id), displayName: r.display_name === null ? null : String(r.display_name ?? ""), activeResumeArtifactKey: r.active_resume_artifact_key === null ? null : String(r.active_resume_artifact_key ?? ""), updatedAt: String(r.updated_at) })); }
  async getCandidate(candidateId: string): Promise<CandidateContext | null> { const candidate = await this.db.prepare(`SELECT candidate_id, display_name, active_resume_artifact_key, profile_json, updated_at FROM interview_candidates WHERE candidate_id = ?`).bind(candidateId).first<Record<string, unknown>>(); if (!candidate) return null; const rows = await (this.db.prepare(`SELECT artifact_key,session_id,artifact_type,file_name,state,created_at FROM artifact_jobs WHERE candidate_id=? ORDER BY created_at DESC LIMIT 100`).bind(candidateId) as Statement).all<Record<string, unknown>>(); let profile: unknown = null; try { profile = candidate.profile_json ? JSON.parse(String(candidate.profile_json)) : null; } catch { profile = null; } return { candidateId, displayName: candidate.display_name === null ? null : String(candidate.display_name ?? ""), activeResumeArtifactKey: candidate.active_resume_artifact_key === null ? null : String(candidate.active_resume_artifact_key ?? ""), updatedAt: String(candidate.updated_at), profile, artifacts: rows.results.map((r) => ({ artifactKey: String(r.artifact_key), sessionId: String(r.session_id), artifactType: String(r.artifact_type), fileName: String(r.file_name), state: r.state as ArtifactState, createdAt: String(r.created_at) })) }; }
  async artifactForRead(candidateId: string, artifactKey: string): Promise<{ r2Key: string; contentType: string; fileName: string } | null> { const row = await this.db.prepare(`SELECT r2_key, content_type, file_name FROM artifact_jobs WHERE candidate_id=? AND artifact_key=? AND state='synced'`).bind(candidateId, artifactKey).first<Record<string, unknown>>(); return row ? { r2Key: String(row.r2_key), contentType: String(row.content_type), fileName: String(row.file_name) } : null; }
  async loadContentForRead(candidateId: string, artifactKey: string): Promise<Uint8Array | null> { const row = await this.db.prepare(`SELECT artifact_contents.content FROM artifact_contents JOIN artifact_jobs USING (artifact_key) WHERE artifact_jobs.candidate_id=? AND artifact_jobs.artifact_key=? AND artifact_jobs.state='synced'`).bind(candidateId, artifactKey).first<{ content: ArrayBuffer | Uint8Array }>(); if (!row?.content) return null; return row.content instanceof Uint8Array ? new Uint8Array(row.content) : new Uint8Array(row.content); }
  async load(jobId: string): Promise<(ArtifactJob & { artifact: ArtifactSubmission }) | null> { const row = await this.db.prepare(`SELECT job_id,artifact_key,candidate_id,session_id,state,metadata_json FROM artifact_jobs WHERE job_id=?`).bind(jobId).first<Record<string, unknown>>(); if (!row) return null; try { return { ...map(row), artifact: JSON.parse(String(row.metadata_json)) as ArtifactSubmission }; } catch { return null; } }
  async state(jobId: string): Promise<ArtifactState | null> { const row = await this.db.prepare(`SELECT state FROM artifact_jobs WHERE job_id=?`).bind(jobId).first<{ state: ArtifactState }>(); return row?.state ?? null; }
  async loadContent(jobId: string): Promise<Uint8Array | null> { const row = await this.db.prepare(`SELECT artifact_contents.content FROM artifact_contents JOIN artifact_jobs USING (artifact_key) WHERE artifact_jobs.job_id = ?`).bind(jobId).first<{ content: ArrayBuffer | Uint8Array }>(); if (!row?.content) return null; return row.content instanceof Uint8Array ? new Uint8Array(row.content) : new Uint8Array(row.content); }
  async claimDispatch(jobId: string, owner: string, until: Date): Promise<ArtifactJob | null> { const now = new Date().toISOString(); await this.db.prepare(`UPDATE artifact_jobs SET state='dispatching',lease_owner=?,lease_until=?,updated_at=? WHERE job_id=? AND state='dispatch_pending'`).bind(owner, until.toISOString(), now, jobId).run(); const row=await this.db.prepare(`SELECT job_id,artifact_key,candidate_id,session_id,state FROM artifact_jobs WHERE job_id=? AND state='dispatching' AND lease_owner=?`).bind(jobId,owner).first<Record<string,unknown>>(); return row?map(row):null; }
  async markQueued(jobId: string, owner: string, messageId: string): Promise<boolean> { const now=new Date().toISOString(); const r=await this.db.prepare(`UPDATE artifact_jobs SET state='broker_queued',broker_message_id=?,lease_owner=NULL,lease_until=NULL,updated_at=? WHERE job_id=? AND state='dispatching' AND lease_owner=?`).bind(messageId,now,jobId,owner).run(); return r.meta?.changes===1; }
  async releaseDispatch(jobId:string, owner:string, code:string):Promise<void>{await this.db.prepare(`UPDATE artifact_jobs SET state='dispatch_pending',dispatch_attempts=dispatch_attempts+1,last_error_code=?,lease_owner=NULL,lease_until=NULL,updated_at=? WHERE job_id=? AND state='dispatching' AND lease_owner=?`).bind(code,new Date().toISOString(),jobId,owner).run();}
  async claimSync(jobId:string,owner:string,until:Date):Promise<ArtifactJob|null>{const now=new Date().toISOString();await this.db.prepare(`UPDATE artifact_jobs SET state='syncing',lease_owner=?,lease_until=?,updated_at=? WHERE job_id=? AND state='broker_queued'`).bind(owner,until.toISOString(),now,jobId).run();const row=await this.db.prepare(`SELECT job_id,artifact_key,candidate_id,session_id,state FROM artifact_jobs WHERE job_id=? AND state='syncing' AND lease_owner=?`).bind(jobId,owner).first<Record<string,unknown>>();return row?map(row):null;}
  async markSynced(jobId:string,owner:string):Promise<boolean>{const now=new Date().toISOString();const r=await this.db.prepare(`UPDATE artifact_jobs SET state='synced',lease_owner=NULL,lease_until=NULL,completed_at=?,updated_at=?,last_error_code=NULL WHERE job_id=? AND state='syncing' AND lease_owner=?`).bind(now,now,jobId,owner).run();return r.meta?.changes===1;}
  async markSyncedAndClearContent(jobId:string,owner:string):Promise<boolean>{const synced=await this.markSynced(jobId,owner); if (!synced) return false; await this.db.prepare(`DELETE FROM artifact_contents WHERE artifact_key = (SELECT artifact_key FROM artifact_jobs WHERE job_id = ? AND state = 'synced')`).bind(jobId).run(); return true;}
  async releaseSync(jobId:string,owner:string,code:string):Promise<boolean>{const r=await this.db.prepare(`UPDATE artifact_jobs SET state='broker_queued',lease_owner=NULL,lease_until=NULL,last_error_code=?,updated_at=? WHERE job_id=? AND state='syncing' AND lease_owner=?`).bind(code,new Date().toISOString(),jobId,owner).run();return r.meta?.changes===1;}
  async seal(jobId:string,owner:string,code:string):Promise<boolean>{const r=await this.db.prepare(`UPDATE artifact_jobs SET state='needs_attention',lease_owner=NULL,lease_until=NULL,last_error_code=?,updated_at=? WHERE job_id=? AND state='syncing' AND lease_owner=?`).bind(code,new Date().toISOString(),jobId,owner).run();return r.meta?.changes===1;}
  private async byKey(key:string):Promise<Record<string,unknown>|null>{return this.db.prepare(`SELECT job_id,artifact_key,candidate_id,session_id,state,sha256 FROM artifact_jobs WHERE artifact_key=?`).bind(key).first<Record<string,unknown>>();}
  private async upsertCandidate(artifact:ArtifactSubmission, now:string):Promise<void>{let profile: string | null = null; if (artifact.artifactType === "profile_update") { try { profile = JSON.stringify(JSON.parse(new TextDecoder().decode(artifact.bytes))); } catch { profile = null; } } await this.db.prepare(`INSERT INTO interview_candidates(candidate_id,display_name,active_resume_artifact_key,profile_json,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(candidate_id) DO UPDATE SET active_resume_artifact_key=COALESCE(excluded.active_resume_artifact_key,interview_candidates.active_resume_artifact_key),profile_json=COALESCE(excluded.profile_json,interview_candidates.profile_json),updated_at=excluded.updated_at`).bind(artifact.candidateId,null,artifact.artifactType==="resume_parsed"?artifact.artifactKey:null,profile,now).run();}
}
