import { describe, expect, it } from "vitest";
import { createSyncHandler } from "../src/sync.js";
import { InMemoryJobRepository } from "../src/db.js";
import type { DestinationAdapter } from "../src/drive-adapter.js";
import type { SyncEvent } from "@reliable-drive-sync/protocol/event";

const event: SyncEvent = { schemaVersion: "1", eventId: "e1", eventKey: "u1:lesson:1", type: "lesson", userId: "u1", sourceSkill: "algorithm", destination: "drive", createdAt: "2026-01-01T00:00:00.000Z", payload: {} };
const enc = new TextEncoder(); const b64 = (bytes: Uint8Array) => btoa(String.fromCharCode(...bytes)).replace(/\+/g, "-").replace(/\//g, "_").replace(/=/g, "");
async function signed(body: string, key = "key", claims: Record<string, unknown> = {}) { const head = b64(enc.encode(JSON.stringify({ alg: "HS256", typ: "JWT" }))); const payload = b64(enc.encode(JSON.stringify({ aud: "https://worker/v1/sync", body, exp: Math.floor(Date.now() / 1000) + 60, ...claims }))); const cryptoKey = await crypto.subtle.importKey("raw", enc.encode(key), { name: "HMAC", hash: "SHA-256" }, false, ["sign"]); return `${head}.${payload}.${b64(new Uint8Array(await crypto.subtle.sign("HMAC", cryptoKey, enc.encode(`${head}.${payload}`))))}`; }
async function setup(outcome: Awaited<ReturnType<DestinationAdapter["sync"]>>) { const repo = new InMemoryJobRepository(() => "job-1"); const job = await repo.createOrGet(event); const adapter: DestinationAdapter = { sync: async () => outcome }; const handler = createSyncHandler({ QSTASH_CURRENT_SIGNING_KEY: "key", SYNC_WORKER_URL: "https://worker/v1/sync" }, repo, adapter, () => new Date("2026-01-02"), () => "lease"); const body = JSON.stringify({ jobId: job.jobId, eventKey: event.eventKey, userId: event.userId }); return { repo, adapter, handler, body }; }
describe("signed sync endpoint", () => {
  it("rejects missing, tampered, and expired signatures before Drive", async () => { const { handler, body } = await setup({ kind: "success", syncedAt: "x" }); expect((await handler(new Request("https://worker/v1/sync", { method: "POST", body }))).status).toBe(489); const bad = await signed(`${body}x`); expect((await handler(new Request("https://worker/v1/sync", { method: "POST", body, headers: { "Upstash-Signature": bad } }))).status).toBe(489); const expired = await signed(body, "key", { exp: 1 }); expect((await handler(new Request("https://worker/v1/sync", { method: "POST", body, headers: { "Upstash-Signature": expired } }))).status).toBe(489); });
  it("accepts next key rotation and maps success/retry/permanent safely", async () => { const { handler, body, repo } = await setup({ kind: "success", syncedAt: "x" }); const sig = await signed(body, "key"); expect((await handler(new Request("https://worker/v1/sync", { method: "POST", body, headers: { "Upstash-Signature": sig } }))).status).toBe(204); expect(repo.getDispatchJob("job-1")?.state).toBe("synced"); });
  it("does not call Drive when envelope substitutes a task", async () => { const { handler } = await setup({ kind: "success", syncedAt: "x" }); const body = JSON.stringify({ jobId: "job-1", eventKey: "u1:other", userId: "u1" }); const sig = await signed(body); expect((await handler(new Request("https://worker/v1/sync", { method: "POST", body, headers: { "Upstash-Signature": sig } }))).status).toBe(489); });
  it("returns bounded retry-after for rate limit", async () => { const { handler, body, repo } = await setup({ kind: "retryable", code: "drive_rate_limited", retryAfterMs: 5000 }); const response = await handler(new Request("https://worker/v1/sync", { method: "POST", body, headers: { "Upstash-Signature": await signed(body) } })); expect(response.status).toBe(503); expect(response.headers.get("Retry-After")).toBe("5"); expect(repo.getDispatchJob("job-1")?.state).toBe("broker_queued"); });
});
