import { describe, expect, it } from "vitest";
import { createFailureCallbackHandler, createSyncHandler } from "../src/sync.js";
import { InMemoryJobRepository } from "../src/db.js";
import { createProductionDriveAdapter, type DestinationAdapter } from "../src/drive-adapter.js";
import type { SyncEvent } from "@reliable-drive-sync/protocol/event";

const event: SyncEvent = { schemaVersion: "1", eventId: "e1", eventKey: "u1:lesson:1", type: "lesson", userId: "u1", sourceSkill: "algorithm", destination: "drive", createdAt: "2026-01-01T00:00:00.000Z", payload: {} };
const enc = new TextEncoder(); const b64 = (bytes: Uint8Array) => btoa(String.fromCharCode(...bytes)).replace(/\+/g, "-").replace(/\//g, "_").replace(/=/g, "");
async function signed(body: string, key = "key", claims: Record<string, unknown> = {}, alg = "HS256") { const head = b64(enc.encode(JSON.stringify({ alg, typ: "JWT" }))); const payload = b64(enc.encode(JSON.stringify({ aud: "https://worker/v1/sync", body, exp: Math.floor(Date.now() / 1000) + 60, ...claims }))); const cryptoKey = await crypto.subtle.importKey("raw", enc.encode(key), { name: "HMAC", hash: "SHA-256" }, false, ["sign"]); return `${head}.${payload}.${b64(new Uint8Array(await crypto.subtle.sign("HMAC", cryptoKey, enc.encode(`${head}.${payload}`))))}`; }
async function setup(outcome: Awaited<ReturnType<DestinationAdapter["sync"]>>) { const repo = new InMemoryJobRepository(() => "job-1"); const job = await repo.createOrGet(event); repo.addDispatchJob({ jobId: job.jobId, eventKey: event.eventKey, userId: event.userId, state: "broker_queued", dispatchAttempts: 0, lastErrorCode: null, brokerMessageId: "q1", leaseOwner: null, leaseUntil: null }); const adapter: DestinationAdapter = { sync: async () => outcome }; const handler = createSyncHandler({ QSTASH_CURRENT_SIGNING_KEY: "key", QSTASH_NEXT_SIGNING_KEY: "next", SYNC_WORKER_URL: "https://worker/v1/sync" }, repo, adapter, () => new Date("2026-01-02"), () => "lease"); const body = JSON.stringify({ jobId: job.jobId, eventKey: event.eventKey, userId: event.userId }); return { repo, adapter, handler, body }; }
describe("signed sync endpoint", () => {
  it("accepts signed terminal callbacks once and rejects invalid or foreign callbacks without mutation", async () => {
    const repo = new InMemoryJobRepository(() => "job-1"); const job = await repo.createOrGet(event);
    repo.addDispatchJob({ jobId: job.jobId, eventKey: event.eventKey, userId: event.userId, state: "broker_queued", dispatchAttempts: 0, lastErrorCode: null, brokerMessageId: "m", leaseOwner: null, leaseUntil: null });
    const url = "https://worker/v1/qstash/failure"; const handler = createFailureCallbackHandler({ QSTASH_CURRENT_SIGNING_KEY: "key", QSTASH_NEXT_SIGNING_KEY: "next", QSTASH_FAILURE_CALLBACK_URL: url }, repo);
    const raw = JSON.stringify({ body: JSON.stringify({ jobId: "job-1", eventKey: event.eventKey, userId: event.userId }) });
    const request = (signature?: string) => new Request(url, { method: "POST", body: raw, headers: signature ? { "Upstash-Signature": signature } : {} });
    expect((await handler(request())).status).toBe(489); expect(repo.getDispatchJob("job-1")?.state).toBe("broker_queued");
    const valid = await signed(raw, "key", { aud: url }); expect((await handler(request(valid))).headers.get("Upstash-NonRetryable-Error")).toBe("true"); expect((await repo.listOpenNotices("u1")).length).toBe(1);
    expect((await handler(request(await signed(raw, "next", { aud: url })))).status).toBe(489); expect((await repo.listOpenNotices("u1")).length).toBe(1);
    const foreign = JSON.stringify({ body: JSON.stringify({ jobId: "missing", eventKey: event.eventKey, userId: event.userId }) }); expect((await handler(new Request(url, { method: "POST", body: foreign, headers: { "Upstash-Signature": await signed(foreign, "key", { aud: url }) } }))).status).toBe(489);
  });
  it("rejects missing, tampered, and expired signatures before Drive", async () => { const { handler, body } = await setup({ kind: "success", syncedAt: "x" }); expect((await handler(new Request("https://worker/v1/sync", { method: "POST", body }))).status).toBe(489); const bad = await signed(`${body}x`); expect((await handler(new Request("https://worker/v1/sync", { method: "POST", body, headers: { "Upstash-Signature": bad } }))).status).toBe(489); const expired = await signed(body, "key", { exp: 1 }); expect((await handler(new Request("https://worker/v1/sync", { method: "POST", body, headers: { "Upstash-Signature": expired } }))).status).toBe(489); });
  it("accepts next key rotation and maps success/retry/permanent safely", async () => { const { handler, body, repo } = await setup({ kind: "success", syncedAt: "x" }); const sig = await signed(body, "key"); expect((await handler(new Request("https://worker/v1/sync", { method: "POST", body, headers: { "Upstash-Signature": sig } }))).status).toBe(204); expect(repo.getDispatchJob("job-1")?.state).toBe("synced"); });
  it("accepts the rotated next signing key and rejects nbf, algorithm, and URL mismatch", async () => { const { handler, body } = await setup({ kind: "success", syncedAt: "x" }); const next = await signed(body, "next"); expect((await handler(new Request("https://worker/v1/sync", { method: "POST", body, headers: { "Upstash-Signature": next } }))).status).toBe(204); const { handler: nbfHandler, body: nbfBody } = await setup({ kind: "success", syncedAt: "x" }); const nbf = await signed(nbfBody, "key", { nbf: Math.floor(Date.now() / 1000) + 60 }); expect((await nbfHandler(new Request("https://worker/v1/sync", { method: "POST", body: nbfBody, headers: { "Upstash-Signature": nbf } }))).status).toBe(489); });
  it("rejects an algorithm and audience mismatch even with a valid MAC", async () => { const { handler, body } = await setup({ kind: "success", syncedAt: "x" }); expect((await handler(new Request("https://worker/v1/sync", { method: "POST", body, headers: { "Upstash-Signature": await signed(body, "key", {}, "HS512") } }))).status).toBe(489); const { handler: audienceHandler, body: audienceBody } = await setup({ kind: "success", syncedAt: "x" }); expect((await audienceHandler(new Request("https://worker/v1/sync", { method: "POST", body: audienceBody, headers: { "Upstash-Signature": await signed(audienceBody, "key", { aud: "https://wrong/v1/sync" }) } }))).status).toBe(489); });
  it("does not call Drive when envelope substitutes a task", async () => { const { handler } = await setup({ kind: "success", syncedAt: "x" }); const body = JSON.stringify({ jobId: "job-1", eventKey: "u1:other", userId: "u1" }); const sig = await signed(body); expect((await handler(new Request("https://worker/v1/sync", { method: "POST", body, headers: { "Upstash-Signature": sig } }))).status).toBe(489); });
  it("returns bounded retry-after for rate limit", async () => { const { handler, body, repo } = await setup({ kind: "retryable", code: "drive_rate_limited", retryAfterMs: 5000 }); const response = await handler(new Request("https://worker/v1/sync", { method: "POST", body, headers: { "Upstash-Signature": await signed(body) } })); expect(response.status).toBe(503); expect(response.headers.get("Retry-After")).toBe("5"); expect(repo.getDispatchJob("job-1")?.state).toBe("broker_queued"); });
  it("never acknowledges a lost lease or dispatch_pending job", async () => { const { handler, body, repo } = await setup({ kind: "success", syncedAt: "x" }); repo.markSynced = async () => false; expect((await handler(new Request("https://worker/v1/sync", { method: "POST", body, headers: { "Upstash-Signature": await signed(body) } }))).status).toBe(503); const fresh = await setup({ kind: "success", syncedAt: "x" }); fresh.repo.addDispatchJob({ jobId: "job-1", eventKey: event.eventKey, userId: event.userId, state: "dispatch_pending", dispatchAttempts: 0, lastErrorCode: null, brokerMessageId: null, leaseOwner: null, leaseUntil: null }); expect((await fresh.handler(new Request("https://worker/v1/sync", { method: "POST", body: fresh.body, headers: { "Upstash-Signature": await signed(fresh.body) } }))).status).toBe(503); });
  it("keeps a valid signed job retryable when default Drive parent configuration is absent", async () => { const repo = new InMemoryJobRepository(() => "job-1"); const job = await repo.createOrGet(event); repo.addDispatchJob({ jobId: job.jobId, eventKey: event.eventKey, userId: event.userId, state: "broker_queued", dispatchAttempts: 0, lastErrorCode: null, brokerMessageId: "q1", leaseOwner: null, leaseUntil: null }); const body = JSON.stringify({ jobId: job.jobId, eventKey: event.eventKey, userId: event.userId }); const handler = createSyncHandler({ QSTASH_CURRENT_SIGNING_KEY: "key", SYNC_WORKER_URL: "https://worker/v1/sync" }, repo, createProductionDriveAdapter({})); expect((await handler(new Request("https://worker/v1/sync", { method: "POST", body, headers: { "Upstash-Signature": await signed(body) } }))).status).toBe(503); expect(repo.getDispatchJob("job-1")?.state).toBe("broker_queued"); });
  it("opens one durable notice before a permanent acknowledgement and safely handles duplicate delivery", async () => { const { handler, body, repo } = await setup({ kind: "permanent", code: "drive_request_rejected" }); const sig = await signed(body); const request = () => new Request("https://worker/v1/sync", { method: "POST", body, headers: { "Upstash-Signature": sig } }); expect((await handler(request())).status).toBe(489); expect((await repo.listOpenNotices("u1")).length).toBe(1); expect(repo.getDispatchJob("job-1")?.state).toBe("needs_attention"); const duplicate = await handler(request()); expect(duplicate.status).toBe(489); expect(duplicate.headers.get("Upstash-NonRetryable-Error")).toBe("true"); });
});
